# Build stage
FROM node:20 as builder

# Declaring environment variables
ENV NODE_ENV production

# Create and set the working directory
WORKDIR /app

# Install app dependencies
COPY ./package.json ./
RUN npm install

# Bundle app source
COPY . .

# Build the app
RUN npm run build

# Serve stage
FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]