version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    ports:
      - "3001:3001"
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: postgres-container
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - /home/curry/postgresql/data:/var/lib/postgresql/data
    networks:
      - app-network

  flask_api:
    build:
      context: ../NTPU_carcrash
      dockerfile: Dockerfile.flask
    networks:
      - app-network
    environment:
      - FLASK_PORT=3005
    ports:
      - "3005:3005"

networks:
  app-network:
    driver: bridge
