# Test signup (normal user)
POST http://localhost:3001/api/users/signup
Content-Type: application/json

{
  "username": "user",
  "password": "user",
  "role": "normal-user"
}

###

# Test signup (admin) 
POST http://localhost:3001/api/users/signup
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "role": "super-user"
}

###

# Test login (normal user)
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "username": "user",
  "password": "user"
}

###

# Test login (admin)
POST http://163.13.172.18:3001/api/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

# Test login (admin)
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


###

# Test logout
GET http://localhost:3001/api/users/logout

###

# Get all users
GET http://localhost:3001/api/users/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6InN1cGVyLXVzZXIifSwiaWF0IjoxNzE0NjI4MzQ4LCJleHAiOjE3MTQ2MzE5NDh9.iacLuqjQLlDtWrNilags_9uaKaG5Sb4R4EFr70xvlJA

###

# Test update user
PUT http://localhost:3001/api/users/update/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6InN1cGVyLXVzZXIifSwiaWF0IjoxNzE0NjIwODY4LCJleHAiOjE3MTQ2MjQ0Njh9.4FRf0r6-vJbp-jZzB4pTSiJnO2RKTp6RJdzNY8v8PHI

{
  "username": "user1",
  "password": "user1",
  "role": "normal-user"
}

###

# Test delete user
DELETE http://localhost:3001/api/users/delete/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6InN1cGVyLXVzZXIifSwiaWF0IjoxNzE0NjIwODY4LCJleHAiOjE3MTQ2MjQ0Njh9.4FRf0r6-vJbp-jZzB4pTSiJnO2RKTp6RJdzNY8v8PHI

###

# Test change password
PUT http://localhost:3001/api/users/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6InN1cGVyLXVzZXIifSwiaWF0IjoxNzE0NjQxNDQ1LCJleHAiOjE3MTQ2NDUwNDV9.Crq_zmyU7R3EqD-DDzqun89gqNroWr5OyOoH5V05Ivg

{
  "username": "user",
  "password": "user123"
}
